Intial commits
Sunbird-Knowlg/sunbird-framework-management-ui-tool pull request #3
Opened 2023-07-14 10:00 UTC by katakampranavi

![sunbird-framework-management-tool-snapshot]- https://drive.google.com/file/d/1kdX56m_iqZAEbhI9EYB3T2ozhVmP4QQ7/view?usp=sharing

2023-07-17 07:27 UTC, HarishGangula commented
The footer will be bottom of the page

2023-07-17 07:28 UTC, HarishGangula commented
replace logo icon from. react to sunbird

2023-07-17 07:29 UTC, HarishGangula requested changes

2023-07-17 07:29 UTC, HarishGangula commented on sunbird-framework-management-tool/src/App.js
> +        style={{
No inline style allowed

2023-07-17 11:05 UTC, katakampranavi commented
@HarishGangula As suggested i made the changes please find below link for snapshot
https://drive.google.com/file/d/1TD_1x0MdLSQ9L3baRBrTy-ywBbB-t6YK/view?usp=sharing

2023-07-17 12:11 UTC, HarishGangula requested changes

2023-07-17 12:11 UTC, HarishGangula commented on sunbird-framework-management-tool/public/index.html
> +    <title>React App</title>
Change this title to `sunbird framework management tool`

2023-07-17 12:24 UTC, katakampranavi commented
@HarishGangula title name changed from react to sunbird framework management tool
https://drive.google.com/file/d/1XFUe1CGMlOE9ZFUMYbQ4kppI45CXUwK1/view?usp=sharing

2023-07-18 03:41 UTC, HarishGangula approved these changes

2023-07-18 05:00 UTC, merged